[workspace]
members = ["crates/libxrk", "crates/libxrk-python"]
resolver = "2"

[workspace.dependencies]
arrow = { version = "57", default-features = false }
binrw = "0.14"
flate2 = "1"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = 1
strip = "none"
